### ISSUE TITLE
Implement more reusable section and utility components

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#348]
We currently have the following reusable component:

* MediaObject

Survey implemented pages and pages in Figma for more candidates for reusable components. 

We may want to generalize the table component present in the milestone component and papersarchive page. PR #373 has started implementing such a component.

We may also want to preemptively make components for Tailwind UI components that look to be generally useful.

So far, I have identified the following categories of components:
* Page templates with a title section
* Sections such as a call to action
* Collections of components such as a card list or card grid
* Basic components such as a card or a table
* Element components which closely map to individual html elements such as a "p" element

**Comment by ghost** [comment]
The events section on the "Around the Web" page looks like a good candidate for a reusable component.

**Comment by ghost** [comment]
I'm going to create a reusable container for the stacked list used in Around the Web. 

![image](https://user-images.githubusercontent.com/1385802/119907704-dd709880-bf1e-11eb-898d-86f941350dbf.png)

- [ ] Await post merge review feedback on PR #388, and act upon requested changes as they are received.

**Comment by ghost** [comment]
I believe this trailing link occurs within many components:

![image](https://user-images.githubusercontent.com/1385802/120045307-aa410e80-bfdd-11eb-871b-0346266aafdf.png)

I'll consider implementing a small reusable component for this pattern. In general, a section component will usually have a grid or flex layout, header text and footer text. We might be able to build a collection of section layout, header, and footer components.

**Comment by ghost** [comment]
I'll start generalizing the highlights in quadrant component that exists in the News page.

- [ ] Address any post merge review comments for PR #393

**Comment by ghost** [comment]
As part of this work, we may also introduce a collection of common types used to provide content to a reusable component. One example of such a type is a labelled link.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for PR #401.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for PR #446.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for PR #447.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for #448.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for #451.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for #457.

**Comment by ghost** [comment]
- [ ] Address any post merge review comments for #463.

**Comment by ghost** [comment]
I need to finish implementing `/pages/storybook.res` soon so that people can at least quickly glance at what components are available.

**Comment by ghost** [comment]
We are not going to do the code reviews noted above. I am closing this issue now that various components have been implemented. We will create follow-up issues for individual components.
